CHANGELOG.md
sonar-project.properties
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.99.0/CHANGELOG.md)

chore(release): 1.99.0

---

CHANGELOG.md
sonar-project.properties
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/1.99.0/CHANGELOG.md)

chore(merge-back): 1.99.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.103.0/CHANGELOG.md)

chore(release): 1.103.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.104.0/CHANGELOG.md)

chore(release): 1.104.0

---

source/patterns/@aws-solutions-constructs/aws-s3-step-function/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/__snapshots__/s3-step-function.test.js.snap
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/integ.pre-existing-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/integ.s3-step-function-no-argument.expected.json

[159](https://github.com/awslabs/aws-solutions-constructs/issues/159)
Update aws-s3-step-function to trigger for MultiPart Upload and Object Copy

feat  (Issue 159 - Respond to MultiPart Uploads)

---

source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/integ.overrideProperties.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/integ.overrideProperties.ts

*Issue #, if available:* [194](https://github.com/awslabs/aws-solutions-constructs/issues/194)
*Description of changes:* Fixing failing aws-cloudfront-mediastore integ test

fix (aws-cloudfront-mediastore integ tests failing)

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.106.1/CHANGELOG.md)

chore(release): 1.106.1

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.108.1/CHANGELOG.md)

chore(release): 1.108.1

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.109.0/CHANGELOG.md)

chore(release): 1.109.0

---

.viperlightignore
CHANGELOG.md
source/lerna.json
source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb/test/integ.deployFunctionWithExistingVpc.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-secretsmanager/test/integ.deployFunctionWithExistingVpc.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-ssmstringparameter/test/integ.deployFunctionWithExistingVpc.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-lambda/test/__snapshots__/s3-lambda.test.js.snap
source/patterns/@aws-solutions-constructs/aws-s3-lambda/test/integ.existing-s3-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-lambda/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/integ.creatingNewQueue.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/integ.existingQueue.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/integ.existingS3Bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/integ.noArguments.expected.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.110.0/CHANGELOG.md)

chore(release): 1.110.0

---

source/patterns/@aws-solutions-constructs/aws-apigateway-iot/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/test/integ.no-arguments.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb/lib/index.ts
source/patterns/@aws-solutions-constructs/core/lib/apigateway-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/cloudfront-distribution-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/cloudwatch-log-group-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/cognito-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/elasticsearch-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/lambda-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/s3-bucket-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/sagemaker-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/secretsmanager-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/security-group-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/step-function-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/utils.ts
source/patterns/@aws-solutions-constructs/core/lib/vpc-helper.ts
source/patterns/@aws-solutions-constructs/core/test/test-helper.ts

*Issue #, if available:* [228](https://github.com/awslabs/aws-solutions-constructs/issues/228)
Change code to add cfn_nag suppression messages to metadata rather than overwriting metadata
Closes #228 

fix (Add to metadata instead of replacing metadata)

---

source/patterns/@aws-solutions-constructs/aws-lambda-sns/package.json
source/patterns/@aws-solutions-constructs/core/lib/utils.ts

[273](https://github.com/awslabs/aws-solutions-constructs/issues/273)
Corrected utils.ts to handle missing member in conditional statement.
closes 273

fix (Correct "rules_to_suppress" error in utils.ts)

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.114.0/CHANGELOG.md)

chore(release): 1.114.0

---

.viperlightignore
source/patterns/@aws-solutions-constructs/aws-lambda-sqs-lambda/README.md
source/patterns/@aws-solutions-constructs/aws-lambda-sqs-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-sqs-lambda/package.json
source/patterns/@aws-solutions-constructs/aws-lambda-sqs-lambda/test/integ.deployProducerFunctionWithVpc.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-sqs-lambda/test/integ.deployProducerFunctionWithVpc.ts
source/patterns/@aws-solutions-constructs/aws-lambda-sqs-lambda/test/lambda-sqs-lambda.test.ts

*Issue #149 , if available:*
-Added VPC support for aws-lambda-sqs-lambda
-Added tests with vpc deployment

feat(aws-lambda-sqs-lambda) added VPC support for aws-lambda-sqs-lambda

---

CHANGELOG.md

[Internal] Update Changelog.md

chore (Update CHANGELOG.md)

---

source/patterns/@aws-solutions-constructs/aws-sns-sqs/test/integ.deployStandardQueue.expected.json
source/patterns/@aws-solutions-constructs/aws-sns-sqs/test/integ.deployStandardQueue.ts
source/patterns/@aws-solutions-constructs/aws-sns-sqs/test/sns-sqs.test.ts
source/patterns/@aws-solutions-constructs/core/lib/sqs-helper.ts

*Issue #345 , if available:*
-Set fifo to undefined if it is false

feat(aws-sns-sqs) convert SQS fifo: false to fifo: undefined automatically

---

source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/README.md
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/__snapshots__/eventbridge-lambda.test.js.snap
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/eventbridge-lambda.test.ts
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/integ.eventbridge-existing-eventbus.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/integ.eventbridge-existing-eventbus.ts
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/integ.eventbridge-new-eventbus.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/integ.eventbridge-new-eventbus.ts
source/patterns/@aws-solutions-constructs/core/index.ts
source/patterns/@aws-solutions-constructs/core/lib/eventbridge-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/events-rule-defaults.ts
source/patterns/@aws-solutions-constructs/core/lib/input-validation.ts
source/patterns/@aws-solutions-constructs/core/test/__snapshots__/eventbridge-helper.test.js.snap
source/patterns/@aws-solutions-constructs/core/test/eventbridge-helper.test.ts

Enhanced the solutions construct to support existing custom EventBus or creating a new EventBus based on user provided EventBusProps

feat(aws-eventbridge-lambda):  Support for custom EventBus

---

CHANGELOG.md
source/lerna.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/README.md
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/__snapshots__/eventbridge-lambda.test.js.snap
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/eventbridge-lambda.test.ts
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/integ.eventbridge-existing-eventbus.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/integ.eventbridge-existing-eventbus.ts
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/integ.eventbridge-new-eventbus.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-lambda/test/integ.eventbridge-new-eventbus.ts
source/patterns/@aws-solutions-constructs/core/index.ts
source/patterns/@aws-solutions-constructs/core/lib/eventbridge-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/events-rule-defaults.ts
source/patterns/@aws-solutions-constructs/core/lib/input-validation.ts
source/patterns/@aws-solutions-constructs/core/test/__snapshots__/eventbridge-helper.test.js.snap
source/patterns/@aws-solutions-constructs/core/test/eventbridge-helper.test.ts

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.119.0/CHANGELOG.md)

chore(release): 1.119.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.120.0/CHANGELOG.md)

chore(release): 1.120.0

---

source/patterns/@aws-solutions-constructs/core/lib/eventbridge-helper.ts

*Issue #, if available:* 
Fix the import statement for cdk v2 rewrite import utility to work

chore(cdk-v2-import-fix): Fix the import statement for cdk v2 rewrite import utility to work

---

CHANGELOG.md
DESIGN_GUIDELINES.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.122.0/CHANGELOG.md)

chore(release): 1.122.0

---

source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisstreams/README.md
source/patterns/@aws-solutions-constructs/aws-events-rule-kinesisstreams/README.md

*Issue #384 , if available:*
-Updated README with pattern prop cloudwatch.Alarms[]
fixes #384

fix(aws-eventbridge-kinesisstreams): updated README with pattern prop cloudwatch.Alarms[]

---

source/patterns/@aws-solutions-constructs/aws-s3-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-s3-lambda/test/s3-lambda.test.ts
source/patterns/@aws-solutions-constructs/aws-s3-sqs/README.md
source/patterns/@aws-solutions-constructs/aws-s3-sqs/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/integ.customLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/integ.customLoggingBucket.ts
source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/test.s3-sqs.test.ts

*Issue #412 , if available:*
-Added loggingBucketProps in aws-s3-sqs
-Updated README with with new prop

feat(aws-s3-sqs): added loggingBucketProps in aws-s3-sqs and updated tests

---

deployment/v2/align-version.js
source/tools/cdk-integ-tools/bin/cdk-integ-assert-v2.ts

*Issue #, if available:* [416](https://github.com/awslabs/aws-solutions-constructs/issues/416)

fix(cdk-integ-assert-v2): revert the changes for special CDK v2 handling

---

DESIGN_GUIDELINES.md
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/README.md
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.customLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.customLoggingBucket.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/test.cloudfront-s3.test.ts

*Issue #412 , if available:*
-Added loggingBucketProps for cloudfront-s3
-Added integ and unit tests for loggingBucketProps

feat(aws-cloudfront-s3): added loggingBucketProps for cloudfront-s3

---

source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/README.md
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.customLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.customLoggingBucket.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existing-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existing-logging-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existing-logging-bucket.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existingStreamObj.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existingStreamObj.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.no-arguments.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/test.kinesisfirehose-s3.test.ts

*Issue #485 , if available:*
-Added logS3AccessLogs and LoggingBucket props
-Created integ and unit tests for logging bucket
-Added pattern prop S3BucketInterface

feat(aws-kinesisstreams-kinesisfirehose-s3): added loggingBucketProps and logS3AccessLogs

---

source/patterns/@aws-solutions-constructs/aws-lambda-s3/README.md
source/patterns/@aws-solutions-constructs/aws-lambda-s3/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/integ.customLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/integ.customLoggingBucket.ts
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/integ.deployFunction.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/integ.deployFunction.ts
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/integ.deployFunctionWithVpc.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/integ.deployFunctionWithVpc.ts
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/integ.existingFunction.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/integ.existingFunction.ts
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/integ.pre-existing-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/integ.pre-existing-bucket.ts
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/lambda-s3.test.ts

*Issue #485 , if available:*
-Added logS3AccessLogs construct prop and s3BucketInterface
-Updated README with new props
-Updated integ tests with no logging bucket
-Improve tests for 100% coverage, deleted repetitive conditions that were covered in input-validation.ts

feat(aws-lambda-s3): added logS3AccessLogs and updated tests

---

source/patterns/@aws-solutions-constructs/aws-s3-lambda/README.md
source/patterns/@aws-solutions-constructs/aws-s3-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-s3-lambda/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-lambda/test/integ.no-arguments.ts
source/patterns/@aws-solutions-constructs/aws-s3-lambda/test/s3-lambda.test.ts

*Issue #485 , if available:*
-Added logS3AccessLogs construct prop and s3BucketInterface
-Updated README with new props
-Updated integ tests with no logging bucket
-Improve tests for 100% coverage, deleted repetitive conditions that were covered in input-validation.ts

feat(aws-s3-lambda): added logS3AccessLogs and S3BucketInterface

---

source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/README.md
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.existing-job.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.existing-job.ts

*Issue #503 , if available:*
-Encrypted existing script s3 bucket 
fixes #503

feat(aws-kinesisstreams-gluejob): encrypted bucket in existing job integ test

---

source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/README.md

*Issue #, if available:* n/a
*Description of changes:* Tiny README change, updating a reference from the previous `existingBucketInterface` to the new `existingBucketObj`. 

fix(Update reference from `existingBucketInterface` to `existingBucketObj`): Update Documentation

---

source/package.json
source/patterns/@aws-solutions-constructs/core/package.json

…in core/package.json
*Issue #, if available: 526*

Fix for v1 & v2 build failure 

---

CHANGELOG.md
source/lerna.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.no-arguments.ts
source/patterns/@aws-solutions-constructs/core/test/glue-job-helper.test.ts

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.131.0/CHANGELOG.md)

chore(release): 1.131.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.132.0/CHANGELOG.md)

chore(release): 1.132.0

---

CHANGELOG.md
deployment/v2/align-version.js
source/lerna.json
source/patterns/@aws-solutions-constructs/aws-apigateway-kinesisstreams/test/integ.apigateway-kinesis-overwrite.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-lambda/test/integ.deployFunction.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-lambda/test/integ.deployFunction.ts
source/patterns/@aws-solutions-constructs/aws-apigateway-lambda/test/integ.existingFunction.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-lambda/test/integ.existingFunction.ts
source/patterns/@aws-solutions-constructs/aws-apigateway-lambda/test/test.apigateway-lambda.test.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.customCloudfrontLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.customCloudfrontLoggingBucket.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.no-arguments.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.override-behavior.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.override-behavior.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/test/integ.customCloudfrontLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/test/integ.customCloudfrontLoggingBucket.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/test/integ.no-arguments.ts
source/patterns/@aws-solutions-constructs/aws-cognito-apigateway-lambda/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-wafwebacl-cloudfront/test/integ.wafwebacl-cloudfront-apigateway-lambda.expected.json
source/patterns/@aws-solutions-constructs/aws-wafwebacl-cloudfront/test/integ.wafwebacl-cloudfront-apigateway-lambda.ts

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.135.0/CHANGELOG.md)

chore(release): 1.135.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.136.0/CHANGELOG.md)

chore(release): 1.136.0

---

source/patterns/@aws-solutions-constructs/aws-iot-sqs/README.md
source/patterns/@aws-solutions-constructs/aws-iot-sqs/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/README.md

*Issue #403 , if available:*
-Updated README to address missing/misplaced properties
fixes #403

feat(aws-iot-sqs and aws-kinesisstreams-gluejob): updated README

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.138.1/CHANGELOG.md)

chore(release): 1.138.1

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.142.0/CHANGELOG.md)

chore(release): 1.142.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.143.0/CHANGELOG.md)

chore(release): 1.143.0

---

deployment/v2/align-version.js
source/patterns/@aws-solutions-constructs/aws-iot-s3/package.json
source/patterns/@aws-solutions-constructs/core/package.json

*Issue #, if available: [426](https://github.com/awslabs/aws-solutions-constructs/issues/426)*
*Description of changes:* Re-enable DotNET builds

chore(dotnet): Re-enable DotNET builds

---

source/package.json
source/tools/cdk-integ-tools/bin/cdk-integ-assert-v2.ts
source/tools/cdk-integ-tools/bin/cdk-integ-assert.ts
source/tools/cdk-integ-tools/lib/canonicalize-assets.ts
source/tools/cdk-integ-tools/lib/integ-helpers.ts
source/tools/cdk-integ-tools/package.json

*Issue #, if available: [539](https://github.com/awslabs/aws-solutions-constructs/issues/539)*
*Description of changes:* Refresh the internal code for cdk-integ

chore(cdk-integ-tools): sync with the main codebase

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.145.0/CHANGELOG.md)

chore(release): 1.145.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.146.0/CHANGELOG.md)

chore(release): 1.146.0

---

source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda-elasticsearch-kibana/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda-elasticsearch-kibana/test/integ.no-arguments.ts
source/patterns/@aws-solutions-constructs/aws-dynamodbstreams-lambda-elasticsearch-kibana/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-dynamodbstreams-lambda-elasticsearch-kibana/test/integ.no-arguments.ts
source/patterns/@aws-solutions-constructs/aws-lambda-elasticsearch-kibana/test/integ.domain-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-elasticsearch-kibana/test/integ.domain-arguments.ts
source/patterns/@aws-solutions-constructs/aws-lambda-elasticsearch-kibana/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-elasticsearch-kibana/test/integ.no-arguments.ts

fixes Issue 620
Make cognito domain names more obscure to avoid collisions

chore(aws-lambda-elasticsearch-kibana): Fix integration test generation

---

source/patterns/@aws-solutions-constructs/aws-sqs-lambda/README.md

docs(aws-sqs-lambda): Fix typo

---

CHANGELOG.md
source/lerna.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/README.md
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/fakefile.py
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.code-asset-job.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.code-asset-job.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/test.kinesisstream-gluejob.test.ts
source/patterns/@aws-solutions-constructs/core/lib/glue-job-defaults.ts
source/patterns/@aws-solutions-constructs/core/lib/glue-job-helper.ts
source/patterns/@aws-solutions-constructs/core/test/glue-job-helper.test.ts
source/use_cases/aws-custom-glue-etl/lib/aws-custom-glue-etl-stack.ts

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.148.0/CHANGELOG.md)

chore(release): 1.148.0

---

source/patterns/@aws-solutions-constructs/aws-fargate-s3/README.md
source/patterns/@aws-solutions-constructs/aws-fargate-s3/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-fargate-s3/test/fargate-s3.test.ts
source/patterns/@aws-solutions-constructs/aws-fargate-sqs/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-fargate-sqs/test/fargate-sqs.test.ts
source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/test/iot-lambda-dynamodb.test.ts
source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb/test/lambda-dynamodb.test.ts
source/patterns/@aws-solutions-constructs/aws-lambda-s3/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-s3/test/lambda-s3.test.ts
source/patterns/@aws-solutions-constructs/aws-lambda-ssmstringparameter/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-ssmstringparameter/test/lambda-ssmstringparameter.test.ts
source/patterns/@aws-solutions-constructs/core/lib/input-validation.ts
source/patterns/@aws-solutions-constructs/core/test/input-validation.test.ts

chore(Check permission inputs): Add a check for bucketPermissions, queuePermissions, etc.

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.151.0/CHANGELOG.md)

chore(release): 1.151.0

---

source/patterns/@aws-solutions-constructs/aws-route53-alb/lib/index.ts
source/patterns/@aws-solutions-constructs/core/lib/vpc-helper.ts

While reviewing the VPC helper code looking to improve the architecture, decided the design is actually decent but it was hidden by hard to read code. 

chore(readability): Made code more readable

---

source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/integ.customLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/integ.pre-existing-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/integ.pre-existing-bucket.ts
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/integ.s3-step-function-no-argument.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-stepfunctions/README.md
source/patterns/@aws-solutions-constructs/aws-s3-stepfunctions/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-s3-stepfunctions/test/integ.customLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-stepfunctions/test/integ.customLoggingBucket.ts
source/patterns/@aws-solutions-constructs/aws-s3-stepfunctions/test/integ.pre-existing-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-stepfunctions/test/integ.pre-existing-bucket.ts
source/patterns/@aws-solutions-constructs/aws-s3-stepfunctions/test/integ.s3-stepfunctions-no-argument.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-stepfunctions/test/s3-stepfunctions.test.ts

*Issue #565 , if available:*
- Changed escape hatch to eventBridgeEnabled prop
- Generated new integ expected JSON
- Updated unit tests for Custom EventBridge Enabled 
fixes #565

feat(aws-s3-stepfunctions): Changed escape hatch to eventBridgeEnabled prop

---

source/patterns/@aws-solutions-constructs/aws-apigateway-kinesisstreams/test/integ.apigateway-kinesis-overwrite.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-kinesisstreams/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisstreams/test/integ.eventbridge-kinesisstreams-existing-eventbus.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisstreams/test/integ.eventbridge-kinesisstreams-existing.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisstreams/test/integ.eventbridge-kinesisstreams-new-eventbus.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisstreams/test/integ.eventbridge-kinesisstreams-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-events-rule-kinesisstreams/test/integ.events-rule-kinesisstreams-existing-eventbus.expected.json
source/patterns/@aws-solutions-constructs/aws-events-rule-kinesisstreams/test/integ.events-rule-kinesisstreams-existing.expected.json
source/patterns/@aws-solutions-constructs/aws-events-rule-kinesisstreams/test/integ.events-rule-kinesisstreams-new-eventbus.expected.json
source/patterns/@aws-solutions-constructs/aws-events-rule-kinesisstreams/test/integ.events-rule-kinesisstreams-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-iot-kinesisstreams/test/integ.existing-kinesisstream.expected.json
source/patterns/@aws-solutions-constructs/aws-iot-kinesisstreams/test/integ.new-kinesisstream.expected.json
source/patterns/@aws-solutions-constructs/aws-iot-kinesisstreams/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.code-asset-job.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.existing-job.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.customLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existing-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existing-logging-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existingStreamObj.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/test/integ.existing.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/core/lib/kinesis-streams-helper.ts

Issue #663 
Changed it from 1 month to the documented 12 hours

fix(Change Kinesis Storage Threshold): Change to the documented 12 hours

---

source/use_cases/aws-custom-glue-etl/test/integ.gluejob.expected.json
source/use_cases/aws-restaurant-management-demo/.eslintignore
source/use_cases/aws-restaurant-management-demo/bin/restaurant-management-system-demo.ts
source/use_cases/aws-restaurant-management-demo/package.json
source/use_cases/aws-restaurant-management-demo/test/__snapshots__/existingResourcesStack.test.js.snap
source/use_cases/aws-restaurant-management-demo/test/__snapshots__/kitchenStaffStack.test.js.snap
source/use_cases/aws-restaurant-management-demo/test/__snapshots__/managerStack.test.js.snap
source/use_cases/aws-restaurant-management-demo/test/__snapshots__/serviceStaffStack.test.js.snap
source/use_cases/aws-restaurant-management-demo/test/__snapshots__/sharedStack.test.js.snap
source/use_cases/aws-s3-static-website/test/__snapshots__/s3-static-site-stack.test.js.snap
source/use_cases/aws-s3-static-website/test/integ.basic-deployment.expected.json
source/use_cases/aws-s3-static-website/test/s3-static-site-stack.test.ts
source/use_cases/aws-serverless-image-handler/lib/index.ts
source/use_cases/aws-serverless-image-handler/test/__snapshots__/test.serverless-image-handler.test.js.snap
source/use_cases/aws-serverless-image-handler/test/integ.basic-deployment.expected.json
source/use_cases/aws-serverless-image-handler/test/test.serverless-image-handler.test.ts
source/use_cases/aws-serverless-image-handler/tsconfig.json
source/use_cases/aws-serverless-web-app/test/__snapshots__/s3-static-site-stack.test.js.snap
source/use_cases/aws-serverless-web-app/test/__snapshots__/serverless-backend-stack.test.js.snap
source/use_cases/aws-serverless-web-app/test/integ.001-s3-static-website-deployment.expected.json
source/use_cases/aws-serverless-web-app/test/integ.002-backend-deployment.expected.json
source/use_cases/aws-serverless-web-app/test/s3-static-site-stack.test.ts
source/use_cases/license-header.js

Issue #668 
The use cases aren't built as part of the regular process and have become outdated. This PR ensures they build with current components. 
Additional PRs are needed to align the build process with the rest of constructs, add to build-patterns.sh and move to CDK V2

chore(use case refresh): Bring use cases up to date

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.153.1/CHANGELOG.md)

chore(release): 1.153.1

---

source/patterns/@aws-solutions-constructs/core/package.json

Pin core to the last version of @types/prettier that works

fix(@types/prettier): Pin-to-the-last-working-version

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.156.1/CHANGELOG.md)

chore(release): 1.156.1

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/1.156.1/CHANGELOG.md)

chore(merge-back): 1.156.1

---

source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/test/apigateway-sqs.test.ts
source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/test/integ.existing-queue.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/test/integ.existing-queue.ts

*Issue #716 , if available:*
- Added unit and integ test for an existing queue
fixes #716

feat(aws-apigateway-sqs): added existing queue tests

---

CHANGELOG.v2.md
deployment/v2/align-version.js
source/lerna.v2.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.10.0/CHANGELOG.md)

chore(release): 2.10.0

---

CHANGELOG.v2.md
source/lerna.v2.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.15.0/CHANGELOG.md)

chore(release): 2.15.0

---

CHANGELOG.v2.md
deployment/v2/align-version.js
source/lerna.v2.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.15.0/CHANGELOG.md)

chore(merge-back): 2.15.0

---

CHANGELOG.v2.md
source/lerna.v2.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.16.0/CHANGELOG.md)

chore(release): 2.16.0

---

CHANGELOG.v2.md
deployment/v2/align-version.js
source/lerna.v2.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.16.0/CHANGELOG.md)

chore(merge-back): 2.16.0

---

CHANGELOG.v2.md
source/lerna.v2.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.17.0/CHANGELOG.md)

chore(release): 2.17.0

---

CHANGELOG.v2.md
deployment/v2/align-version.js
source/lerna.v2.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.17.0/CHANGELOG.md)

chore(merge-back): 2.17.0

---

CONTRIBUTING.md
deployment/align-version.sh
deployment/build-patterns.sh
deployment/v2/allow-partial-builds.sh

Add code to all V1 scripts alerting developers not to use them, update CONTRIBUTE.md to create V2 builds.

chore(Turn off V1): Turn off V1 scripts and update developer docs

---

CHANGELOG.md
CONTRIBUTING.md
deployment/align-version.sh
deployment/build-patterns.sh
deployment/v2/allow-partial-builds.sh
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.19.0/CHANGELOG.md)

chore(release): 2.19.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.20.0/CHANGELOG.md)

chore(release): 2.20.0

---

source/package.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-sns/lib/index.ts

Closes #782 
Upgrade Typescript to 4.7.4, address associated issues. Remove dependency on specific version of @types/prettier

Upgrade to Typescript 4.7.4

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.22.0/CHANGELOG.md)

chore(release): 2.22.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.23.0/CHANGELOG.md)

chore(release): 2.23.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.24.0/CHANGELOG.md)

chore(merge-back): 2.24.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.25.0/CHANGELOG.md)

chore(release): 2.25.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.25.0/CHANGELOG.md)

chore(merge-back): 2.25.0

---

source/tools/cdk-integ-tools/bin/cdk-integ-assert.ts
source/tools/cdk-integ-tools/bin/cdk-integ.ts

closes #804 
Removes references to deprecated feature flags in the cdk-integ tools

fix(cdk-integ): remove deprecated feature flags

---

source/patterns/@aws-solutions-constructs/aws-apigateway-kinesisstreams/test/integ.apigateway-kinesis-overwrite.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-kinesisstreams/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisstreams/test/integ.eventbridge-kinesisstreams-existing-eventbus.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisstreams/test/integ.eventbridge-kinesisstreams-existing.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisstreams/test/integ.eventbridge-kinesisstreams-new-eventbus.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisstreams/test/integ.eventbridge-kinesisstreams-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-iot-kinesisstreams/test/integ.existing-kinesisstream.expected.json
source/patterns/@aws-solutions-constructs/aws-iot-kinesisstreams/test/integ.new-kinesisstream.expected.json
source/patterns/@aws-solutions-constructs/aws-iot-kinesisstreams/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.code-asset-job.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.existing-job.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.customLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existing-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existing-logging-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.existingStreamObj.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/test/integ.existing.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/test/integ.no-arguments.expected.json
source/patterns/@aws-solutions-constructs/core/lib/kinesis-streams-helper.ts

*Issue #663 , if available:*
fixes #663 
-Updated threshold unit from seconds to milliseconds

fix(kinesis-streams-helper): updated threshold unit from seconds to milliseconds

---

source/patterns/@aws-solutions-constructs/aws-alb-fargate/README.md
source/patterns/@aws-solutions-constructs/aws-alb-lambda/README.md
source/patterns/@aws-solutions-constructs/aws-route53-alb/README.md
source/patterns/@aws-solutions-constructs/aws-wafwebacl-alb/README.md

-Removed account numbers from READMEs

chore(READMEs): Removed account numbers

---

source/package.json
source/tools/cdk-integ-tools/package.json

pin the version of @types/babel__traverse to resolve the issue introduced by the release of 7.18.3

chore(fix dependency issue): fix the build

---

CHANGELOG.md
source/lerna.json

v1-bump/1.175.0

---

CHANGELOG.md
source/lerna.json

v1-bump/1.176.0

---

CHANGELOG.md
source/lerna.json

v1-bump/1.177.0

---

CHANGELOG.md
source/lerna.json

v1-bump/1.178.0

---

CHANGELOG.md
source/lerna.json

v1-bump/1.179.0

---

CHANGELOG.md
source/lerna.json

v1-bump/1.180.0

---

CHANGELOG.md
source/lerna.json

v1-bump/1.181.0

---

source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/test/integ.existing-waf-to-multiple-gateways.expected.json
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/test/integ.no-arguments.expected.json

Closes #899 
Remove hardcoded partition in arn definition for apigateway resource

feat(aws-wafwebacl-agigateway): enable govcloud

---

source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/test/integ.partial-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/test/integ.partial-arguments.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/test/test.wafwebacl-apigateway.test.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-appsync/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-appsync/test/integ.partial-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-wafwebacl-appsync/test/integ.partial-arguments.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-appsync/test/test.wafwebacl-appsync.test.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-cloudfront/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-cloudfront/test/integ.partial-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-wafwebacl-cloudfront/test/integ.partial-arguments.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-cloudfront/test/test.wafwebacl-cloudfront.test.ts
source/patterns/@aws-solutions-constructs/core/lib/waf-helper.ts
source/patterns/@aws-solutions-constructs/core/test/waf-helper.test.ts

#916 
Allow user to specify any subset of props attributes

feat(wafwebacl-other): allow any type for webAclProps

---

README.md

chore(readme.md): explain versioning issues

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.41.0/CHANGELOG.md)

chore(release): 2.41.0

---

CHANGELOG.md
source/lerna.json
source/patterns/@aws-solutions-constructs/aws-lambda-kendra/package.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.43.1/CHANGELOG.md)

chore(release): 2.43.1

---

CHANGELOG.md
source/lerna.json
source/patterns/@aws-solutions-constructs/aws-lambda-kendra/package.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.44.0/CHANGELOG.md)

chore(release): 2.44.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.44.0/CHANGELOG.md)

chore(merge-back): 2.44.0

---

deployment/v2/build-patterns.sh

chore(build-patterns.sh): remove $(npm bin) reference

---

source/patterns/@aws-solutions-constructs/core/lib/fargate-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/glue-job-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/sagemaker-helper.ts
source/patterns/@aws-solutions-constructs/core/test/fargate-helper.test.ts

chore(sonarqube): address more cognitive complexity issues

---

source/patterns/@aws-solutions-constructs/aws-fargate-dynamodb/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-fargate-dynamodb/test/fargate-dynamodb.test.ts
source/patterns/@aws-solutions-constructs/aws-fargate-sns/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-fargate-sns/test/fargate-sns.test.ts
source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/test/iot-lambda-dynamodb.test.ts
source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb/test/lambda-dynamodb.test.ts
source/patterns/@aws-solutions-constructs/aws-lambda-sns/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-sns/test/lambda-sns.test.ts
source/patterns/@aws-solutions-constructs/aws-sns-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-sns-lambda/test/sns-lambda.test.ts
source/patterns/@aws-solutions-constructs/aws-sns-sqs/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-sns-sqs/test/sns-sqs.test.ts
source/patterns/@aws-solutions-constructs/core/lib/fargate-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/input-validation.ts
source/patterns/@aws-solutions-constructs/core/test/input-validation.test.ts

chore(all): clean up more sonarqube issues (input-validation)

---

source/patterns/@aws-solutions-constructs/aws-alb-fargate/test/alb-fargate.test.ts
source/patterns/@aws-solutions-constructs/aws-alb-lambda/test/alb-lambda.test.ts
source/patterns/@aws-solutions-constructs/aws-route53-alb/test/route53-alb.test.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-alb/lib/index.ts
source/patterns/@aws-solutions-constructs/core/lib/alb-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/input-validation.ts
source/patterns/@aws-solutions-constructs/core/test/alb-helper.test.ts
source/patterns/@aws-solutions-constructs/core/test/input-validation.test.ts

chore(all): move alb prop checks

---

source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/cloudfront-mediastore.test.ts
source/patterns/@aws-solutions-constructs/aws-lambda-sagemakerendpoint/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-sagemakerendpoint/test/aws-lambda-sagemakerendpoint.test.ts
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/core/lib/alb-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/input-validation.ts
source/patterns/@aws-solutions-constructs/core/test/input-validation.test.ts

chore(main): two more checkprops functions to address code smells

---

refresh-multiple-tests.sh
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.kinglu-code-asset-job.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/integ.kinglu-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/test/kinesisstream-gluejob.test.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.kinfhss3-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/test/integ.kinfhss3-no-arguments.ts
source/patterns/@aws-solutions-constructs/core/lib/glue-job-helper.ts
source/patterns/@aws-solutions-constructs/core/test/glue-job-helper.test.ts

chore(all): more integration test cleanup

---

source/patterns/@aws-solutions-constructs/aws-lambda-sqs/test/integ.lamsqs-useCmk.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-sqs/test/integ.lamsqs-useCmk.ts

Create a test that creates a CMK to verify policy creation

chore(aws-lambda-sqs): add a test that explicitly creates a cmk key

---

source/package.json
source/patterns/@aws-solutions-constructs/core/package.json

Fixes #1074 
Upgrades library version to address vulnerability discussed in Issue 1074

fix(npmlog): update npmlog version

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.58.1/CHANGELOG.md)

chore(release): 2.58.1

---

deployment/v2/align-version.js

chore(all): updated cdk to latest version

---

deployment/v2/align-version.js

chore(all): update cdk version

---

CHANGELOG.md
deployment/v2/align-version.js
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.66.0/CHANGELOG.md)

chore(release): 2.66.0

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.67.0/CHANGELOG.md)

chore(release): 2.67.0

---

CHANGELOG.md
deployment/v2/align-version.js
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.67.1/CHANGELOG.md)

chore(merge-back): 2.67.1

---

deployment/v2/align-version.js

chore(all): update underlying cdk version

---

CHANGELOG.md
deployment/v2/align-version.js
source/lerna.json
source/package.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.76.0/CHANGELOG.md)

chore(merge-back): 2.76.0

---

source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/README.md
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/lib/index.ts

chore(aws-cloudfront-mediastore): add warnings about discontinuation of service

---

CHANGELOG.md
source/release-info.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.85.4/CHANGELOG.md)

chore(release): 2.85.4

---

CHANGELOG.md
source/release-info.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.85.5/CHANGELOG.md)

chore(release): 2.85.5

---

CHANGELOG.md
source/release-info.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.85.6/CHANGELOG.md)

chore(release): 2.85.6

---

source/package-lock.json
source/release-info.json

chore(all): advance version number

---

CHANGELOG.md
source/package-lock.json
source/release-info.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.90.0/CHANGELOG.md)

chore(release): 2.90.0

---

CHANGELOG.md
source/release-info.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.90.1/CHANGELOG.md)

chore(release): 2.90.1

---

CHANGELOG.md
source/package-lock.json
source/release-info.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.90.2/CHANGELOG.md)

chore(merge-back): 2.90.2

---

CHANGELOG.md
source/release-info.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.90.3/CHANGELOG.md)

chore(merge-back): 2.90.3

---

CHANGELOG.md
source/release-info.json
source/use_cases/aws-s3-static-website/lib/website-dist/index.html

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/merge-back/2.90.4/CHANGELOG.md)

chore(merge-back): 2.90.4

---

source/package-lock.json
source/patterns/@aws-solutions-constructs/eslintrc.config.mjs
source/use_cases/aws-restaurant-management-demo/THIRD_PARTY_LICENSE.txt
source/use_cases/aws-restaurant-management-demo/lib/lambda/service-staff/create-order/package-lock.json
source/use_cases/aws-restaurant-management-demo/package-lock.json
source/use_cases/aws-s3-static-website/THIRD_PARTY_LICENSE.txt
source/use_cases/aws-s3-static-website/package-lock.json

fix(eslint): fix issue in eslint.config.mjs

---

CHANGELOG.md
deployment/v2/align-version.js
source/release-info.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.92.2/CHANGELOG.md)

chore(release): 2.92.2

---

THIRD_PARTY_LICENSE.txt
source/package-lock.json
source/patterns/@aws-solutions-constructs/aws-dynamodbstreams-pipes-stepfunctions/package.json
source/patterns/@aws-solutions-constructs/aws-sns-sqs/lib/index.ts
source/patterns/@aws-solutions-constructs/core/index.ts
source/patterns/@aws-solutions-constructs/core/lib/constructs-feature-flags.ts
source/patterns/@aws-solutions-constructs/core/package.json
source/patterns/@aws-solutions-constructs/core/test/constructs-feature-flags.test.ts
source/use_cases/aws-restaurant-management-demo/THIRD_PARTY_LICENSE.txt
source/use_cases/aws-s3-static-website/THIRD_PARTY_LICENSE.txt

Define the first flag
Add a custom onSynthesis function that creates a feature flag report artifact in the manifest.

feat(core): add the infrastructure to allow constructs specific feature flags in cdk.json

---

documentation/aws-alb-fargate.adoc
documentation/aws-alb-lambda.adoc
documentation/aws-apigateway-dynamodb.adoc
documentation/aws-apigateway-iot.adoc
documentation/aws-cognito-apigateway-lambda.adoc
documentation/aws-constructs-factories.adoc
documentation/aws-dynamodbstreams-lambda.adoc
documentation/aws-fargate-dynamodb.adoc
documentation/aws-fargate-s3.adoc
documentation/aws-iot-kinesisfirehose-s3.adoc
documentation/aws-iot-lambda-dynamodb.adoc
documentation/aws-iot-lambda.adoc
documentation/aws-iot-sqs.adoc
documentation/aws-kinesisstreams-gluejob.adoc
documentation/aws-lambda-eventbridge.adoc
documentation/aws-lambda-opensearch.adoc
documentation/aws-lambda-secretsmanager.adoc
documentation/aws-lambda-sqs-lambda.adoc
documentation/aws-lambda-ssmstringparameter.adoc
documentation/aws-route53-apigateway.adoc
documentation/aws-s3-sns.adoc
documentation/aws-s3-sqs.adoc
documentation/aws-s3-stepfunctions.adoc
documentation/aws-sns-sqs.adoc
documentation/aws-wafwebacl-alb.adoc
documentation/aws-wafwebacl-apigateway.adoc
documentation/aws-wafwebacl-appsync.adoc
documentation/aws-wafwebacl-cloudfront.adoc

chore(documentation): refresh documentation publication folder
