source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/README.md
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/package.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/test/__snapshots__/test.kinesisstreams-lambda.test.js.snap
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/test/integ.deployFunction.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/test/integ.existing.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/test/integ.existing.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-lambda/test/test.kinesisstreams-lambda.test.ts
source/patterns/@aws-solutions-constructs/core/lib/lambda-event-source-mapping-defaults.ts
source/patterns/@aws-solutions-constructs/core/test/lambda-event-source.test.ts

*Issue #, if available:* #58 
*Description of changes:* This PR adds the ability to bring an existing Kinesis stream to the `aws-kinesisstreams-lambda` pattern. There's also a breaking change in the pattern interface (described below).
**BREAKING CHANGE**: DefaultKinesisEventSourceProps was removed from lambda-event-source-mapping-defaults and replaced with KinesisEventSourceProps. This now follows the same behavior as the aws-dynamodb-stream-lambda and aws-s3-lambda patterns (which use DynamoEventSourceProps and S3EventSourceProps instead of EventSourceMappingOptions)
---

feat(aws-kinesisstreams-lambda): Add ability to bring-your-own stream

---

source/patterns/@aws-solutions-constructs/aws-events-rule-step-function/test/__snapshots__/events-rule-step-function.test.js.snap
source/patterns/@aws-solutions-constructs/aws-events-rule-step-function/test/integ.events-rule-step-function-no-argument.expected.json
source/patterns/@aws-solutions-constructs/aws-events-rule-step-function/test/integ.events-rule-step-function-no-argument.ts
source/patterns/@aws-solutions-constructs/aws-events-rule-step-function/test/integ.events-rule-step-function-with-lambda.expected.json
source/patterns/@aws-solutions-constructs/aws-events-rule-step-function/test/integ.events-rule-step-function-with-lambda.ts
source/patterns/@aws-solutions-constructs/aws-lambda-step-function/test/__snapshots__/lambda-step-function.test.js.snap
source/patterns/@aws-solutions-constructs/aws-lambda-step-function/test/integ.deploy-lambda.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-step-function/test/integ.deploy-lambda.ts
source/patterns/@aws-solutions-constructs/aws-lambda-step-function/test/integ.existing-function.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-step-function/test/integ.existing-function.ts
source/patterns/@aws-solutions-constructs/aws-lambda-step-function/test/lambda-step-function.test.ts
source/patterns/@aws-solutions-constructs/aws-s3-step-function/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/__snapshots__/s3-step-function.test.js.snap
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/integ.pre-existing-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/integ.pre-existing-bucket.ts
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/integ.s3-step-function-no-argument.expected.json
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/integ.s3-step-function-no-argument.ts
source/patterns/@aws-solutions-constructs/aws-s3-step-function/test/s3-step-function.test.ts
source/patterns/@aws-solutions-constructs/core/lib/step-function-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/utils.ts
source/patterns/@aws-solutions-constructs/core/test/__snapshots__/step-function-helper.test.js.snap
source/patterns/@aws-solutions-constructs/core/test/utils.test.ts

*Issue #, if available:* T047 (internal)
Log groups used by Step Functions must start with /aws/vendedlog/states or the policy generated to access the logs is too long. But each log file must have a unique name. Formerly we used to let CFN assign a random name, but that stopped working in the past 6 months. We can't instruct CFN to create a random name with a fixed prefix, so the PR creates a unique, but not random, name for each CloudWatch Logs group using a very similar method to the CDK - concatenating a portion of all the IDs in the construct tree and appending a hash created using all of the IDs in the construct tree.

T047 - Fix CloudWatch Log Policy Size in Step Functions construct

---

source/patterns/@aws-solutions-constructs/aws-lambda-sagemakerendpoint/test/__snapshots__/aws-lambda-sagemakerendpoint.test.js.snap
source/patterns/@aws-solutions-constructs/aws-lambda-secretsmanager/test/integ.deployFunctionWithExistingVpc.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-secretsmanager/test/integ.deployFunctionWithVpc.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-sns/test/integ.deployFunctionWithVpc.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-sqs/test/integ.deployFunctionWithVpc.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-ssmstringparameter/test/integ.deployFunctionWithExistingVpc.expected.json
source/patterns/@aws-solutions-constructs/aws-lambda-ssmstringparameter/test/integ.deployFunctionWithVpc.expected.json
source/patterns/@aws-solutions-constructs/core/lib/vpc-helper.ts
source/patterns/@aws-solutions-constructs/core/test/__snapshots__/sagemaker-helper.test.js.snap
source/patterns/@aws-solutions-constructs/core/test/vpc-helper.test.ts

210
Change the name given to SecurityGroups assigned to VPC Endpoints to include construct ID and endpoint service.

fix (Eliminate name collision for Security Groups on VPC Endpoints)

---

source/use_cases/aws-serverless-web-app/lib/s3-static-site-stack.ts
source/use_cases/aws-serverless-web-app/lib/serverless-backend-stack.ts

1. Modified the CloudFront settings not to have the Lambda@Edge that modifies the response sent to the users as it's conflicting with the front end Java script execution.
2. Enabled email verification and User Sign up features to the Cognito User Pool settings.

Disabled Lambda-at-edge and enabled email verify

---

source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda-elasticsearch-kibana/README.md
source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda-elasticsearch-kibana/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda/README.md
source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda/test/dynamodb-stream-lambda.test.ts
source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda/test/integ.existing-table.expected.json
source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda/test/integ.existing-table.ts
source/patterns/@aws-solutions-constructs/core/lib/dynamodb-table-helper.ts
source/patterns/@aws-solutions-constructs/core/test/dynamo-table.test.ts

*Issue #, if available:* [119](https://github.com/awslabs/aws-solutions-constructs/issues/119)
Allow users to pass `dynamodb.ITable` for in construct props `existingTableObj` for dynamodb stream patterns

fix(allow ITable for dynamodb stream patterns)

---

source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/__snapshots__/cloudfront-mediastore.test.js.snap
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/integ.default.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/integ.withoutHttpSecurityHeaders.expected.json

#252 
Modified the AWS MediaStore policy condition to only allow the AWS CloudFront user agent. Look at the bug description for more details. 
https://github.com/awslabs/aws-solutions-constructs/issues/252
Tested changes to make sure they have the intended effect of only allowing access to GET request files from the Amazon CloudFront endpoint. GET requests directly to MediaStore endpoint now just return a generic 403 access denied response. 
`
Condition: {
StringEquals: {
'aws:UserAgent': this.cloudFrontOriginAccessIdentity.originAccessIdentityName
},
Bool: {
'aws:SecureTransport': 'true'
}
` …

fix (MediaStore policy fix to deny anonymous user-agents access aws-cloudfront-mediastore) 

---

source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/README.md
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.existing-bucket.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/test.cloudfront-s3.test.ts
source/patterns/@aws-solutions-constructs/core/lib/cloudfront-distribution-defaults.ts
source/patterns/@aws-solutions-constructs/core/lib/cloudfront-distribution-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/input-validation.ts

*Issue #, if available:* [139](https://github.com/awslabs/aws-solutions-constructs/issues/139)
Allow users to pass `s3.IBucket` for in construct props `existingBucketInterface` for aws-cloudfront-s3 pattern

fix (allow IBucket for aws-cloudfront-s3 pattern) (#139)

---

source/patterns/@aws-solutions-constructs/aws-sns-lambda/README.md

Fix typo and reference SnsToLambdaProps correctly.
*Issue #, if available:* N/A
*Description of changes:* Minor typo in the docs.

fix(doc): Typo in aws-sns-lambda README.md

---

source/patterns/@aws-solutions-constructs/aws-apigateway-iot/test/integ.overrideParams.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-iot/test/integ.override_auth_api_keys.expected.json
source/tools/cdk-integ-tools/bin/cdk-integ-assert.ts
source/tools/cdk-integ-tools/bin/cdk-integ.ts

*Issue #, if available:* [396](https://github.com/awslabs/aws-solutions-constructs/issues/396)
Update Cfn templates to match the expected results for CDK v2 and V1

fix(api-usage-plan): update cfn templates with api usage plan

---

CHANGELOG.md
source/lerna.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/1.128.0/CHANGELOG.md)

chore(release): 1.128.0

---

source/tools/cdk-integ-tools/lib/canonicalize-assets.ts
source/tools/cdk-integ-tools/lib/integ-helpers.ts
source/tools/cdk-integ-tools/solutions-constructs-modifications.md

*Issue #, if available: [627](https://github.com/awslabs/aws-solutions-constructs/issues/627)*
*Description of changes: Ignore the diff for S3AutoDeleteObjects lambda function from cdk-integ-assert* 

fix(cdk-integ-tools): Ignore the diff for S3AutoDeleteObjects lambda function from cdk-integ-assert

---

source/patterns/@aws-solutions-constructs/aws-kinesisfirehose-s3/lib/index.ts

The JSON.stringify() call in this statement caused problems
Issue648

fix(Remove debug statement): Remove extra debug statement in kinesisfirehose-s3

---

source/patterns/@aws-solutions-constructs/aws-lambda-elasticachememcached/package.json

aws-lambda-elasticache published with wrong artifact ID - this will cause problems for that construct and for aws-lambda-s3 in releases 1.153.0, 1.153.1 and 2.6.0. After loading this will release 1.154.0 and 2.7.0 ASAP

fix(Incorrect Java Artifact ID): Change lambdas3  lambdaelasticachememcached

---

DESIGN_GUIDELINES.md
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/README.md
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/README.md
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/README.md
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/README.md
source/patterns/@aws-solutions-constructs/aws-wafwebacl-cloudfront/README.md

No
Updated to Distribution because the documentation specified the old CloudFrontWebDistribution.
This was updated in v1.68.0.
https://github.com/awslabs/aws-solutions-constructs/commit/f02997ea4fa6515fc4429771d21821d2c26a8584

docs: Update to Distribution type

---

CONTRIBUTING.md
sonar-project.properties

Update contribution guide to include steps to add coverage reports for new patterns.
Add coverage reports for new contsruct (aws-wafwebacl-appsync).

Update contribution guide to include coverage reports for new patterns

---

sonar-project.properties

This PR updates `sonar-project.properties` file with alphabetically ordered list of coverage report directories from all existing patterns.
Alphabetical order would allow us to do automated checks on this in the future if desired.

Add missing coverage reports in alphabetical order

---

source/patterns/@aws-solutions-constructs/aws-apigateway-iot/README.md

The examples in the aws-apigateway-iot documentation suggest using API-KEY as the authentication mechanism which is against best practices. The construct itself defaults to IAM authentication, so it is fine - just the docs need to be changed.

chore(update docs): remove bad example from apigateway-iot

---

source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/README.md

Closes Issue #886 
When aws-lambda-dynamodb was enhanced, the extra functionality was never added to this L4 construct.

fix(aws-iot-lambda-dynamodb): expose additional aws-dynamodb-lambda functionality

---

source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/README.md
source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/test/integ.iot-lambda-dynamodb.expected.json
source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/test/integ.with-vpc.expected.json
source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/test/integ.with-vpc.ts
source/patterns/@aws-solutions-constructs/aws-iot-lambda-dynamodb/test/iot-lambda-dynamodb.test.ts

Closes #886
VPC functionality and the ability to set the table name environment variable had not been surfaced from the lambda-dynamodb construct within.

feat(aws-iot-lambda-dynamodb): add vpc and environment variable name to construct interface

---

CHANGELOG.md
source/lerna.json
source/patterns/@aws-solutions-constructs/aws-apigateway-dynamodb/README.md
source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/README.md
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/test/integ.existing-waf-to-multiple-gateways.expected.json
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/test/integ.no-arguments.expected.json

See [CHANGELOG](https://github.com/awslabs/aws-solutions-constructs/blob/bump/2.32.0/CHANGELOG.md)

chore(release): 2.32.0

---

source/patterns/@aws-solutions-constructs/aws-apigateway-dynamodb/README.md
source/patterns/@aws-solutions-constructs/aws-apigateway-dynamodb/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-apigateway-dynamodb/test/apigateway-dynamodb.test.ts
source/patterns/@aws-solutions-constructs/aws-apigateway-dynamodb/test/integ.additional-request-templates-custom-resource-name.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-dynamodb/test/integ.additional-request-templates-custom-resource-name.ts

Fixes #848
- Add a resourceName on the `ApiGatewayToDynamoDB` construct

feat(aws-apigateway-dynamodb): add optional resourceName parameter

---

source/patterns/@aws-solutions-constructs/core/lib/lambda-helper.ts
source/patterns/@aws-solutions-constructs/core/test/lambda-helper.test.ts

Currently multiple calls to `buildLambdaFunction()`  with `lambdaFunctionProps` in the same stack throws the following error:
>There is already a Construct with name 'LambdaFunctionServiceRole' in Stack [Default]
Error is caused by a call to `deployLambdaFunction()` with `undefined` as function id. So `deployLambdaFunction` creates a lambda with the same default id for every call.
This PR fixes the issue by passing `lambdaFunctionProps.functionName` as lambda id to `deployLambdaFunction()` and adds 2 new tests to `lambda-helper.test.ts`:
- 'test buildLambdaFunction with lambdaFunctionProps default id' that assures that current behaviour is preserved (when lambdaFunctionProps.functionName is not set a default id will be used)
- 'test buildLambdaFunction with …

fix(core) id conflict with multiple buildLambdaFunction() calls

---

source/patterns/@aws-solutions-constructs/aws-kinesisfirehose-s3/lib/index.ts
source/patterns/@aws-solutions-constructs/core/lib/s3-bucket-helper.ts
source/patterns/@aws-solutions-constructs/core/test/s3-bucket-helper.test.ts

#906 
#907 
Set the loggingBucket on the response object when an existing bucket is supplied.

fix(s3-bucket-helper): not populating response.loggingBucket when bucket supplied

---

source/patterns/@aws-solutions-constructs/aws-alb-fargate/test/integ.all-existing-private-http.expected.json
source/patterns/@aws-solutions-constructs/aws-alb-fargate/test/integ.all-existing-private-http.ts
source/patterns/@aws-solutions-constructs/aws-alb-fargate/test/integ.all-new-public-http.expected.json
source/patterns/@aws-solutions-constructs/aws-alb-fargate/test/integ.all-new-public-http.ts
source/patterns/@aws-solutions-constructs/aws-alb-fargate/test/integ.all-new-two-targets.expected.json
source/patterns/@aws-solutions-constructs/aws-alb-fargate/test/integ.all-new-two-targets.ts

#961 
These integration tests now use a minimal container available publicly in our account so they pass a health check and the integ stack launches when being refreshed

fix(aws-alb-fargate): change container used to launch integ tests

---

source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisfirehose-s3/README.md
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisfirehose-s3/test/eventbridge-kinesisfirehose-s3.test.ts
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisfirehose-s3/test/integ.existingLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-kinesisfirehose-s3/test/integ.existingLoggingBucket.ts
source/patterns/@aws-solutions-constructs/core/lib/s3-bucket-helper.ts
source/patterns/@aws-solutions-constructs/core/test/s3-bucket-helper.test.ts

#965 
Delete line that removed lifecycle rules
Test that and that an existingLogBucket can be sent to aws-eventbridge-kinesisfirehose-s3

fix(s3-bucket-helper): do not remove lifecycle rules from log buckets

---

source/patterns/@aws-solutions-constructs/aws-kinesisfirehose-s3/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-kinesisfirehose-s3/test/integ.two-instances.expected.json
source/patterns/@aws-solutions-constructs/aws-kinesisfirehose-s3/test/integ.two-instances.ts
source/patterns/@aws-solutions-constructs/aws-kinesisfirehose-s3/test/kinesisfirehose-s3.test.ts

Issue #990 
Appended id to the resource name for the aws managed key

fix(aws-kinesisfirehose-s3): resource name collision when two instances deployed in same stack

---

source/patterns/@aws-solutions-constructs/aws-apigateway-dynamodb/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-elasticsearch-kibana/test/lambda-elasticsearch-kibana.test.ts
source/patterns/@aws-solutions-constructs/aws-lambda-opensearch/test/lambda-opensearch.test.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-alb/lib/index.ts
source/patterns/@aws-solutions-constructs/core/lib/alb-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/elasticsearch-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/kendra-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/opensearch-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/s3-bucket-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/sagemaker-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/sns-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/sqs-helper.ts
source/patterns/@aws-solutions-constructs/core/test/sagemaker-helper.test.ts

chore(all): address sonarqube code smells

---

sonar-project.properties
source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-fargate-s3/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-gluejob/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-lambda-kendra/test/lambda-kendra.test.ts
source/patterns/@aws-solutions-constructs/core/lib/input-validation.ts
source/patterns/@aws-solutions-constructs/core/test/glue-job-helper.test.ts
source/patterns/@aws-solutions-constructs/core/test/input-validation.test.ts

Start the process of isolating the tests of props for each service utilized in a construct (break up input-validation.sh)

chore(sonarqube): address more code smells

---

source/patterns/@aws-solutions-constructs/aws-lambda-s3/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-route53-alb/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-route53-apigateway/lib/index.ts
source/patterns/@aws-solutions-constructs/core/lib/kendra-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/sqs-helper.ts

chore(sonarqube): clean up code smells

---

source/patterns/@aws-solutions-constructs/aws-eventbridge-sns/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-eventbridge-sns/test/eventbridge-sns-topic.test.ts
source/patterns/@aws-solutions-constructs/aws-eventbridge-sns/test/integ.exist-bus.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-sns/test/integ.long-stack-name.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-sns/test/integ.long-stack-name.ts
source/patterns/@aws-solutions-constructs/aws-eventbridge-sns/test/integ.new-bus.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-sns/test/integ.second-long-stack-name.expected.json
source/patterns/@aws-solutions-constructs/aws-eventbridge-sns/test/integ.second-long-stack-name.ts

Closes #1015 
Explicitly set the physical name of the Event/Topic binding

fix(aws-eventbridge-sns): long sns topic names break eventbridge bindings

---

source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/test/apigateway-sqs.test.ts
source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/test/integ.apisqs-additional-request-templates.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/test/integ.apisqs-apigateway-sqs-crud.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/test/integ.apisqs-custom-integration-responses.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/test/integ.apisqs-existing-queue.expected.json
source/patterns/@aws-solutions-constructs/aws-apigateway-sqs/test/integ.apisqs-no-arguments.expected.json

- #1029
- Prevent the creation of the /message path when the DELETE method is not used, as this path is only utilized by the DELETE method.

fix(aws-apigateway-sqs): Remove /message path when delete method is not allowed

---

deployment/v2/refresh-multiple-tests.sh
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.cftaplam-customCloudfrontLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.cftaplam-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.cftaplam-override-behavior.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/test/integ.cftapi-customCloudfrontLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/test/integ.cftapi-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/integ.cftmed-customCloudFrontLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/integ.cftmed-default.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/integ.cftmed-existingContainer.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/integ.cftmed-overrideProperties.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/integ.cftmed-withSecurityHeaderBehavior.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-mediastore/test/integ.cftmed-withoutHttpSecurityHeaders.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-custom-headers.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-custom-originPath.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-customLoggingBuckets.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-existing-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-no-security-headers.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/test.cloudfront-s3.test.ts
source/patterns/@aws-solutions-constructs/aws-wafwebacl-cloudfront/lib/index.ts
source/patterns/@aws-solutions-constructs/core/lib/cloudfront-distribution-helper.ts
source/patterns/@aws-solutions-constructs/core/lib/s3-bucket-helper.ts
source/patterns/@aws-solutions-constructs/core/test/cloudfront-distribution-s3-helper.test.ts

Addresses Issue #1041 
Adds s3 access logging to the CloudFront log buckets by default

feat(cloudfront constructs): add s3 access logging to cloudfront access log buckets by default

---

source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/README.md
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/lib/index.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.cftaplam-customCloudfrontLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.cftaplam-customCloudfrontLoggingBucket.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.cftaplam-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.cftaplam-no-arguments.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.cftaplam-override-behavior.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.cftaplam-override-behavior.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/test.cloudfront-apigateway-lambda.test.ts
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/test/integ.cftapi-customCloudfrontLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/test/integ.cftapi-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/test/integ.wafapi-existing-waf-to-multiple-gateways.expected.json
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/test/integ.wafapi-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/test/integ.wafapi-partial-arguments.expected.json
source/patterns/@aws-solutions-constructs/core/lib/apigateway-defaults.ts
source/patterns/@aws-solutions-constructs/core/lib/apigateway-helper.ts
source/patterns/@aws-solutions-constructs/core/test/glue-job-helper.test.ts
source/patterns/@aws-solutions-constructs/core/test/test-helper.ts

Closes #1043
Check incoming props to require explicit auth type
Update all integration tests from no auth to custom auth

feat(aws-cloudfront-apigateway-lambda): require explicit authentication type

---

source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/test.cloudfront-s3.test.ts
source/patterns/@aws-solutions-constructs/core/lib/s3-bucket-helper.ts

In this situation:
```
const cfS3AccessLogBucket = new s3.Bucket(stack, 'cf-s3-access-logs');
new CloudFrontToS3(stack, 'test-cloudfront-s3', {
cloudFrontLoggingBucketProps: {
serverAccessLogsBucket: cfS3AccessLogBucket
}
});
```
The construct will still create an S3 Access Log bucket for the CF log bucket. The provided bucket is ignored. What should happen is that the provided bucket is configured to accept the logs and no additional bucket is created.

fix(aws-cloudfront-s3): do not create s3 access log bucket for cf log bucket when an existing bucket is provided

---

source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-bucket-encrypted-with-cmk-provided-as-existingbucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-bucket-encrypted-with-managed-key-provided-as-existingbucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-cmk-provided-as-bucket-prop.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-custom-headers.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-custom-originPath.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-customCloudFrontLoggingBucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-customLoggingBuckets.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-existing-bucket.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-no-arguments.expected.json
source/patterns/@aws-solutions-constructs/aws-cloudfront-s3/test/integ.cfts3-no-security-headers.expected.json
source/patterns/@aws-solutions-constructs/core/lib/s3-oac-origin.ts

…rement
Currently a stack creating aws-cloudfront-s3 requires IAM permissions for OAIs even though none exist. By
inserting an explicitly empty originAccessIdentity in the S3OriginConfig we remove the CFN requirement for this privilege.

fix(aws-cloudfront-s3): insert empty originAccessIdentity

---

source/patterns/@aws-solutions-constructs/aws-dynamodbstreams-lambda/README.md

I was in this construct to grab a reference to how we configure the dlq on stream processing error, and noticed this bit of the README that seems to be for a different solutions construct (aws-dynamodbstreams-lambda-elasticsearch-kibana). 

fix(aws-dynamodbstreams-lambda) Documentation Update

---

source/patterns/@aws-solutions-constructs/core/lib/lambda-helper.ts

If the client provides a role without a default policy, we need to ensure we don't try to add cfn_nag suppression to the non-existent policy.
This applies to all Lambda based constructs.

fix(aws-eventbridge-lambdba): handle provided role correctly

---

source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/README.md

I recently created a python-based CDK app using the `openapigateway-to-lambda` solutions construct, and noticed a few discrepancies with the example in our README. This PR updates the example code to be correct.

fix(openapigateway-to-lambda): refine python example in README based on deployed code

---

source/patterns/@aws-solutions-constructs/aws-apigateway-iot/package.json
source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/package.json
source/use_cases/aws-custom-glue-etl/package.json
source/use_cases/aws-restaurant-management-demo/lib/lambda/service-staff/create-order/package.json
source/use_cases/aws-restaurant-management-demo/package.json
source/use_cases/aws-restaurant-management-demo/test/integ.basic-deployment.js.snapshot/asset.d7ef2fab3e8af1933261371cc1e90baab16122dc5fca1ca9e5ea26a4720f4eee/package.json
source/use_cases/aws-s3-static-website/package.json

Addresses Issue 1094
Update package.json for aws-kinesisstreams-kinesisfirehose-s3 and 6 other constructs/samples with the same issue.

fix(aws-kinesisstreams-kinesisfirehose-s3): allow later versions of cdk lib by updating peerDependencies

---

source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetExistingLambdaFunctions.js.snapshot/manifest.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetExistingLambdaFunctions.js.snapshot/opilam-apiFromAssetExistingLambdaFunctions.assets.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetExistingLambdaFunctions.js.snapshot/opilam-apiFromAssetExistingLambdaFunctions.template.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetExistingLambdaFunctions.js.snapshot/tree.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetNewLambdaFunctions.js.snapshot/manifest.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetNewLambdaFunctions.js.snapshot/opilam-apiFromAssetNewLambdaFunctions.assets.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetNewLambdaFunctions.js.snapshot/opilam-apiFromAssetNewLambdaFunctions.template.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetNewLambdaFunctions.js.snapshot/tree.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetWithCognitoAuth.js.snapshot/manifest.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetWithCognitoAuth.js.snapshot/opilam-apiFromAssetWithCognitoAuth.assets.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetWithCognitoAuth.js.snapshot/opilam-apiFromAssetWithCognitoAuth.template.json
source/patterns/@aws-solutions-constructs/aws-openapigateway-lambda/test/integ.opilam-apiFromAssetWithCognitoAuth.js.snapshot/tree.json
source/patterns/@aws-solutions-constructs/resources/lib/template-writer.ts
source/patterns/@aws-solutions-constructs/resources/test/integ.template-writer-from-asset.js.snapshot/manifest.json
source/patterns/@aws-solutions-constructs/resources/test/integ.template-writer-from-asset.js.snapshot/template-writer-from-asset.assets.json
source/patterns/@aws-solutions-constructs/resources/test/integ.template-writer-from-asset.js.snapshot/template-writer-from-asset.template.json
source/patterns/@aws-solutions-constructs/resources/test/integ.template-writer-from-large-asset.js.snapshot/manifest.json
source/patterns/@aws-solutions-constructs/resources/test/integ.template-writer-from-large-asset.js.snapshot/template-writer-from-large-asset.assets.json
source/patterns/@aws-solutions-constructs/resources/test/integ.template-writer-from-large-asset.js.snapshot/template-writer-from-large-asset.template.json

Resources provisioned using the construct `@aws-solutions-constructs/aws-openapigateway-lambda` succeed on initial deploy however when a modification is made to the referenced OpenAPI specification the deployment fails. Resulting in the following error.
```
CustomResource attribute error: Vendor response doesn't contain TemplateOutputKey attribute in object arn:aws:cloudformation:ap-southeast-2:000000000000:stack/TestStac
k/1de47700-433e-11ef-8d9f-02222ec9a44d|OpenApiGatewayToLambdaApiTemplateWriterCustomResource957D1BA4|98e1521e-6163-4459-a73d-68f2b50cb336
```
The issue is caused by `./resources/template-writer`. When the specification changes this results in a new S3 asset which is used by `template-writer` to update the inline IAM …

fix(resources/template-writer): add IAM policy as customResource dependency

---

deployment/v2/bootstrap.sh
deployment/v2/build-all.sh
deployment/v2/build-patterns.sh

Take contents of build-patterns.sh and create bootstrap.sh to initialize the docker container and build-all.sh, which actually builds the entire library. In this way when you open a container around an already built codebase you only need to run bootstrap.sh. build-patterns.sh is now pretty much empty - it just invokes these two scripts.By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

chore(build-patterns.sh): split functionality into two scripts

---

source/patterns/@aws-solutions-constructs/aws-alb-fargate/test/alb-fargate.test.ts
source/patterns/@aws-solutions-constructs/aws-alb-lambda/test/alb-lambda.test.ts
source/patterns/@aws-solutions-constructs/core/lib/alb-helper.ts
source/patterns/@aws-solutions-constructs/core/test/alb-helper.test.ts

closes #1159
Remove check that rejected vpc's in loadBalancer props, but confirm if one is received that it is also specified at the construct level

fix(aws-alb-lambda): allow vpc in loadBalancerProps when specifying subnets

---

deployment/v2/align-version.js
source/package.json

A fixed version number slipped into source/package.json and prevented updating the CDK (this was a bug). It is removed to enable us to change CDK versions.

chore(all): update to latest cdk, unlock from fixed version in source/package.json

---

source/patterns/@aws-solutions-constructs/aws-apigateway-iot/README.md

N/a
This PR removes three (3) broken links from the aws-apigateway-iot README file. If the content that these links reference has been moved elsewhere, and they should be updated instead of deleted, please advise in the comments.

docs: remove broken links from aws-apigateway-iot readme

---

source/patterns/@aws-solutions-constructs/core/lib/s3-bucket-helper.ts

Not using a bucket key for a KMS encrypted bucket can drive up costs. This change prints a warning to alert clients to this risk.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-key.html

feat(bucket warning): add a warning if a bucket key is not requested
